server:
  port: 9201

spring:
  application:
    name: lagou-cloud-eureka-server # 应用名称，会在Eureka中作为服务的id标识

eureka:
  client:        # Eureka server本身也是eureka的一个客户端，因为在集群下需要与其它eureka server进行数据的同步
    service-url: # 客户端与EurekaServer交互的地址，如果是集群，也需要写其它Server的地址
      defaultZone: http://LagouCloudEurekaServerA:9200/eureka/
    register-with-eureka: true # 表示是否向Eureka中心注册自己的信息，因为自己就是注册中心
    fetch-registry: true # 是否查询/拉取Eureka Server服务注册列表
  instance:
    #hostname: localhost # 当前Eureka Server实例的主机名
    #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
    #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@
